package com.tuananh.collage.utils

//object FrameUtils {
//    fun initFrameCollageList(): MutableList<IFrame> {
//        val frameList = mutableListOf<IFrame>()
//        frameList.add(IFrame(R.drawable.frame_default_none, true, true))
//        frameList.add(IFrame(R.drawable.frame_collage_19))
//        frameList.add(IFrame(R.drawable.frame_collage_20))
//        frameList.add(IFrame(R.drawable.frame_collage_21))
//        frameList.add(IFrame(R.drawable.frame_collage_22))
//        frameList.add(IFrame(R.drawable.frame_collage_23))
//        frameList.add(IFrame(R.drawable.frame_collage_24))
//        frameList.add(IFrame(R.drawable.frame_collage_25))
//        frameList.add(IFrame(R.drawable.frame_collage_26))
//        frameList.add(IFrame(R.drawable.frame_collage_27))
//        frameList.add(IFrame(R.drawable.frame_collage_28))
//        frameList.add(IFrame(R.drawable.frame_collage_29))
//        frameList.add(IFrame(R.drawable.frame_collage_30))
//        frameList.add(IFrame(R.drawable.frame_collage_31))
//        frameList.add(IFrame(R.drawable.frame_collage_32))
//        frameList.add(IFrame(R.drawable.frame_collage_33))
//        frameList.add(IFrame(R.drawable.frame_collage_34))
//        frameList.add(IFrame(R.drawable.frame_collage_35))
//        frameList.add(IFrame(R.drawable.frame_collage_36))
//        frameList.add(IFrame(R.drawable.frame_collage_37))
//        frameList.add(IFrame(R.drawable.frame_collage_38))
//        frameList.add(IFrame(R.drawable.frame_collage_39))
//        frameList.add(IFrame(R.drawable.frame_collage_46))
//        frameList.add(IFrame(R.drawable.frame_collage_47))
//        frameList.add(IFrame(R.drawable.frame_collage_48))
//        frameList.add(IFrame(R.drawable.frame_collage_49))
//        frameList.add(IFrame(R.drawable.frame_collage_2))
//        frameList.add(IFrame(R.drawable.frame_collage_3))
//        frameList.add(IFrame(R.drawable.frame_collage_11))
//        frameList.add(IFrame(R.drawable.frame_collage_12))
//        frameList.add(IFrame(R.drawable.frame_collage_13))
//        frameList.add(IFrame(R.drawable.frame_collage_14))
//        frameList.add(IFrame(R.drawable.frame_collage_15))
//        frameList.add(IFrame(R.drawable.frame_collage_16))
//        frameList.add(IFrame(R.drawable.frame_collage_17))
//        return frameList
//    }
//}