package com.xiaopo.flying.puzzle.special.template;

import android.content.Context;

import com.xiaopo.flying.puzzle.special.model.ImageRes;
import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;

import java.util.ArrayList;
import java.util.List;

public class Template1 {
    public static void init(List<TemplateRes> resList, Context context, int radius, int customResWidth, int customResHigh, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo;
        List<LibCollagePoint> lstCollagePoints;
        LibCollageInfo cInfo;
        if (customResWidth > 0 && customResHigh > 0) {
            int height;
            int width;
            int top;
            int left;
            if (customResHigh > customResWidth) {
                height = 3060;
                width = (int) (((3060.0f * ((float) customResWidth)) / ((float) customResHigh)) + 0.5f);
                top = 0;
                left = (3060 - width) / 2;
            } else {
                width = 3060;
                height = (int) (((3060.0f * ((float) customResHigh)) / ((float) customResWidth)) + 0.5f);
                left = 0;
                top = (3060 - height) / 2;
            }
            lstCollageInfo = new ArrayList<>();
            lstCollagePoints = new ArrayList<>();
            lstCollagePoints.add(TemplateManager.initCollagePoint(left, top));
            lstCollagePoints.add(TemplateManager.initCollagePoint(left + width, top));
            lstCollagePoints.add(TemplateManager.initCollagePoint(left + width, height + top));
            lstCollagePoints.add(TemplateManager.initCollagePoint(left, height + top));
            lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, 0, 0));
            //resList.add(TemplateManager.initAssetItem("g1_n_c", ImageRes.FitType.TITLE, "template/g1_n_c.png", lstCollageInfo, 10, frameWidth, number));
        }
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(30, 30));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3030, 30));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3030, 3030));
        lstCollagePoints.add(TemplateManager.initCollagePoint(30, 3030));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 30, 30));
        //resList.add(TemplateManager.initAssetItem("g1_1", ImageRes.FitType.TITLE, "template/g1_1.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        cInfo = new LibCollageInfo(lstCollagePoints, 10, 30, 30, "template/mask/mask_heart.png", context);
        cInfo.setIsCanShadow(true);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g1_n_6", ImageRes.FitType.TITLE, "template/g1_n_6.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        cInfo = new LibCollageInfo(lstCollagePoints, 10, 30, 30, "template/mask/mask_circle.png", context);
        cInfo.setIsCanShadow(true);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g1_n_5", ImageRes.FitType.TITLE, "template/g1_n_5.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(933, 386));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1532, 686));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2133, 386));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2680, 850));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2680, 1653));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1533, 2676));
        lstCollagePoints.add(TemplateManager.initCollagePoint(386, 1653));
        lstCollagePoints.add(TemplateManager.initCollagePoint(386, 850));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 30, 30));
        resList.add(TemplateManager.initAssetItem("g1_n_1", ImageRes.FitType.TITLE, "template/g1_n_1.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 310));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2750, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2750));
        lstCollagePoints.add(TemplateManager.initCollagePoint(310, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 30, 30));
        resList.add(TemplateManager.initAssetItem("g1_n_2", ImageRes.FitType.TITLE, "template/g1_n_2.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 310));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2650, 920));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2650, 2138));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2750));
        lstCollagePoints.add(TemplateManager.initCollagePoint(409, 2138));
        lstCollagePoints.add(TemplateManager.initCollagePoint(409, 920));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 30, 30));
        resList.add(TemplateManager.initAssetItem("g1_n_3", ImageRes.FitType.TITLE, "template/g1_n_3.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(852, 64));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2994, 64));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2207, 2994));
        lstCollagePoints.add(TemplateManager.initCollagePoint(63, 2994));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 30, 30));
        resList.add(TemplateManager.initAssetItem("g1_n_4", ImageRes.FitType.TITLE, "template/g1_n_4.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, 0, 0));
        //resList.add(TemplateManager.initAssetItem("g1_2", ImageRes.FitType.TITLE, "template/g1_2.png", lstCollageInfo, 0, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(500, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2560, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2560, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(500, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 0, 0));
        //resList.add(TemplateManager.initAssetItem("g1_3", ImageRes.FitType.TITLE, "template/g1_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 500));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 500));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2560));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2560));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 0, 0));
        //resList.add(TemplateManager.initAssetItem("g1_4", ImageRes.FitType.TITLE, "template/g1_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(750, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2310, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2310, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(750, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 0, 0));
        //resList.add(TemplateManager.initAssetItem("g1_5", ImageRes.FitType.TITLE, "template/g1_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(300, 300));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2760, 300));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2760, 2760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(300, 2760));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, 0, 0));
        //resList.add(TemplateManager.initAssetItem("g1_10", ImageRes.FitType.TITLE, "template/g1_10.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        cInfo = new LibCollageInfo(lstCollagePoints, 10, 30, 30, "template/g1_n_7.png", context);
        cInfo.setIsCanShadow(true);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g1_n_7", ImageRes.FitType.TITLE, "template/g1_n_7.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        cInfo = new LibCollageInfo(lstCollagePoints, 10, 30, 30, "template/g1_n_8.png", context);
        cInfo.setIsCanShadow(true);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g1_n_8", ImageRes.FitType.TITLE, "template/g1_n_8.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        cInfo = new LibCollageInfo(lstCollagePoints, 10, 30, 30, "template/g1_n_9.png", context);
        cInfo.setIsCanShadow(true);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g1_n_9", ImageRes.FitType.TITLE, "template/g1_n_9.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        cInfo = new LibCollageInfo(lstCollagePoints, 10, 30, 30, "template/g1_n_10.png", context);
        cInfo.setIsCanShadow(true);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g1_n_10.png", ImageRes.FitType.TITLE, "template/g1_n_10.png", lstCollageInfo, 10, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        cInfo = new LibCollageInfo(lstCollagePoints, 10, 30, 30, "template/g1_n_11.png", context);
        cInfo.setIsCanShadow(true);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g1_n_11", ImageRes.FitType.TITLE, "template/g1_n_11.png", lstCollageInfo, 10, frameWidth, number));
    }
}
