package com.xiaopo.flying.puzzle.special.template;


import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes;

import java.util.ArrayList;
import java.util.List;

public class Template16 {
    public static void init(List<TemplateRes> resList, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo = new ArrayList<>();
        List<LibCollagePoint> lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_1", ImageRes.FitType.TITLE, "template/g16_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1610));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1610));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1610));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1610));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_2", ImageRes.FitType.TITLE, "template/g16_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1610, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1610, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1610, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1610, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_3", ImageRes.FitType.TITLE, "template/g16_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1440));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1440));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1440));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1440));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_4", ImageRes.FitType.TITLE, "template/g16_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2080));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_5", ImageRes.FitType.TITLE, "template/g16_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1200, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1200, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1200, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2050, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2050, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1200, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2050, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2050, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2050));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2050));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2050));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2050));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2050));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2050));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2050));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2050));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_6", ImageRes.FitType.TITLE, "template/g16_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1000));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1000));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1000));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1000));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_7", ImageRes.FitType.TITLE, "template/g16_7.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 800));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 800));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 800));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 800));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1470));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1470));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1470));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1470));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2360));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2360));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2360));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2360));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_9", ImageRes.FitType.TITLE, "template/g16_9.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(800, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(800, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(800, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(800, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2340, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2340, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2340, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2340, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_10", ImageRes.FitType.TITLE, "template/g16_10.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 720));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 720));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 720));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 720));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1600));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1600));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1600));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1600));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2280));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_11", ImageRes.FitType.TITLE, "template/g16_11.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(700, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(700, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(700, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(700, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2080));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2080));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2080));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2080));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2080));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2080));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g16_12", ImageRes.FitType.TITLE, "template/g16_12.png", lstCollageInfo, radius, frameWidth, number));
    }
}
