package com.xiaopo.flying.puzzle.special.template;


import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes;

import java.util.ArrayList;
import java.util.List;

public class Template17 {
    public static void init(List<TemplateRes> resList, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo = new ArrayList<>();
        List<LibCollagePoint> lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2420));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_1", ImageRes.FitType.TITLE, "template/g17_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1180));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2400, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2400, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1180));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2400, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2400, 1180));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_2", ImageRes.FitType.TITLE, "template/g17_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 660));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_3", ImageRes.FitType.TITLE, "template/g17_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(670, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(670, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(670, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(670, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_4", ImageRes.FitType.TITLE, "template/g17_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 970));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(660, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(660, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(660, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2420, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2420, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(660, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2420, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2420, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_5", ImageRes.FitType.TITLE, "template/g17_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 660));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2420));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_6", ImageRes.FitType.TITLE, "template/g17_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(660, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(660, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1180));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(660, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2420, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2420, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(660, 1180));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2420, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2420, 1180));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1311, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1748, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2186, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2623, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_7", ImageRes.FitType.TITLE, "template/g17_7.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 660));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 437));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2420));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1311));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1748));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2186));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2623));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_8", ImageRes.FitType.TITLE, "template/g17_8.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1630));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1630));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 380));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 380));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 760));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 760));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1140));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1140));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1520));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1520));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1630));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1630));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2280));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2280));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2660));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2100, 2660));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1180, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_9", ImageRes.FitType.TITLE, "template/g17_9.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 1890));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1890));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_10", ImageRes.FitType.TITLE, "template/g17_10.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 380));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1420));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 760));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 760));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1140));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1140));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1520));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1140));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1520));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1520));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2280));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2280));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2660));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2280));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2660));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 2660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 1420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1420));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1890, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_11", ImageRes.FitType.TITLE, "template/g17_11.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1450, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1450, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1180));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1450, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1450, 1180));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 2120));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 2120));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 2120));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 2120));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2120));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 2120));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 2120));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(380, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(760, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1140, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1520, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1900, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2280, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2660, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g17_12", ImageRes.FitType.TITLE, "template/g17_12.png", lstCollageInfo, radius, frameWidth, number));
    }
}
