package com.xiaopo.flying.puzzle.special.template;

import android.content.Context;


import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes.FitType;

import java.util.ArrayList;
import java.util.List;

public class Template3 {
    public static void init(List<TemplateRes> resList, Context context, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo = new ArrayList<>();
        List<LibCollagePoint> lstCollagePoints = new ArrayList<>();
        LibCollageInfo cInfo;
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3_2", FitType.TITLE, "template/g3_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(190, 260));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 260));
        lstCollagePoints.add(TemplateManager.initCollagePoint(960, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(190, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1150, 610));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 610));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1920, 2450));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1150, 2450));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2110, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2880, 970));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2880, 2710));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2110, 2710));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3X_12", FitType.TITLE, "template/Artboard3_12.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3_5", FitType.TITLE, "template/g3_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3_7", FitType.TITLE, "template/g3_7.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1444, 1502));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1444, 1502));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3_n_2", FitType.TITLE, "template/new/3/g3_n_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g3_n_1", FitType.TITLE, "template/new/3/g3_n_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 620));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2440));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 620));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2440));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 620));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2440));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g3_n_3", FitType.TITLE, "template/g3_n_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 340));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2720, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2720));
        lstCollagePoints.add(TemplateManager.initCollagePoint(340, 1530));
        cInfo = new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(455, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 455));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2606, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2606));
        cInfo = new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g3_n_4", FitType.TITLE, "template/g3_n_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1880, 559));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2354, 286));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2828, 559));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2828, 1107));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2354, 1380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1880, 1107));
        cInfo = new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1880, 1953));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2354, 1680));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2828, 1953));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2828, 2501));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2354, 2774));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1880, 2501));
        cInfo = new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g3_n_5", FitType.TITLE, "template/g3_n_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(386, 932));
        lstCollagePoints.add(TemplateManager.initCollagePoint(926, 475));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1490, 757));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1566, 1500));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1452, 2244));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1494, 2722));
        lstCollagePoints.add(TemplateManager.initCollagePoint(386, 1740));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1527, 776));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2133, 475));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2674, 932));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2674, 1740));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1532, 2756));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1487, 2244));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1600, 1500));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g3_n_6", FitType.TITLE, "template/g3_n_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(270, 270));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1390, 270));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1390, 1390));
        lstCollagePoints.add(TemplateManager.initCollagePoint(270, 1390));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(270, 1660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1390, 1660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1390, 2780));
        lstCollagePoints.add(TemplateManager.initCollagePoint(270, 2780));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1660, 270));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2780, 270));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2780, 2810));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1660, 2810));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3X_10", FitType.TITLE, "template/Artboard3_10.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(270, 270));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1390, 270));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1390, 2810));
        lstCollagePoints.add(TemplateManager.initCollagePoint(270, 2810));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1660, 270));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2780, 270));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2780, 1380));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1660, 1380));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1660, 1660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2780, 1660));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2780, 2780));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1660, 2780));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3_13", FitType.TITLE, "template/Artboard3_13.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(240, 120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1100, 120));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1100, 960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(240, 960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1100, 1100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1960, 1100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1960, 1960));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1100, 1960));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1950, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2810, 2080));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2810, 2940));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1950, 2940));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3X_4", FitType.TITLE, "template/Artboard3_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3_1", FitType.TITLE, "template/g3_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3_6", FitType.TITLE, "template/g3_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 612));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1836));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1836));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1836));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1836));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g3_3", FitType.TITLE, "template/g3_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(455, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 455));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2606, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2606));
        cInfo = new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth);
        cInfo.setIsCanCorner(false);
        lstCollageInfo.add(cInfo);
        resList.add(TemplateManager.initAssetItem("g3_n_7", FitType.TITLE, "template/g3_n_7.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2208, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2208, 2335));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2335));
        int i2 = outTerFrameWidth;
        int i3 = outTerFrameWidth;
        List<LibCollagePoint> list = lstCollagePoints;
        lstCollageInfo.add(new LibCollageInfo(list, 0, i2, i3, "template/mask/mask_heart1.png", context));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(696, 923));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2364, 923));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2364, 2469));
        lstCollagePoints.add(TemplateManager.initCollagePoint(696, 2469));
        list = lstCollagePoints;
        lstCollageInfo.add(new LibCollageInfo(list, 0, i2, i3, "template/mask/mask_heart1.png", context));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1682, 1723));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2950, 1723));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2950, 2869));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1682, 2869));
        i2 = outTerFrameWidth;
        i3 = outTerFrameWidth;
        list = lstCollagePoints;
        lstCollageInfo.add(new LibCollageInfo(list, 0, i2, i3, "template/mask/mask_heart1.png", context));
        resList.add(TemplateManager.initAssetItem("g3_n_8", FitType.TITLE, "template/g3_n_8.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(696, 923));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2364, 923));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2364, 2469));
        lstCollagePoints.add(TemplateManager.initCollagePoint(696, 2469));
        list = lstCollagePoints;
        lstCollageInfo.add(new LibCollageInfo(list, 0, i2, i3, "template/mask/mask_heart1.png", context));
        resList.add(TemplateManager.initAssetItem("g3_n_9", FitType.TITLE, "template/g3_n_9.png", lstCollageInfo, radius, frameWidth, number));
    }
}
