package com.xiaopo.flying.puzzle.special.template;


import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes.FitType;

import java.util.ArrayList;
import java.util.List;

public class Template14 {
    public static void init(List<TemplateRes> resList, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo = new ArrayList<>();
        List<LibCollagePoint> lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g14_1", FitType.TITLE, "template/g14_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 383));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 383));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 383));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 383));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 383));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 383));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2678));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2678)); //
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2678));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2678));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g14_2", FitType.TITLE, "template/g14_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2450));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2450));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2550)); //
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2450));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2450));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g14_3", FitType.TITLE, "template/g14_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g14_4", FitType.TITLE, "template/g14_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 600));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 600));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 600));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 600));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1450));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1450));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1450));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1450));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g14_5", FitType.TITLE, "template/g14_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2200, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2200, 1210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1210));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2200, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 860));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2200, 860));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2200, 860));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 860));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2200, 1210));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2100));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 1210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 1210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2100));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g14_6", FitType.TITLE, "template/g14_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1470));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1470));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1470));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1470));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2000));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2000));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2000));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2000));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2000));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2000));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(700, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(700, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(700, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(700, 900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2360, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2360, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2360, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2360, 900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 1400));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1400));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1400));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 1400));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 1400));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1400));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1400));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 1400));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 2200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 2200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(900, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1700, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2380, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g14_8", FitType.TITLE, "template/g14_8.png", lstCollageInfo, radius, frameWidth, number));
    }
}
