package com.xiaopo.flying.puzzle.special.template;

import android.view.accessibility.AccessibilityNodeInfo;

import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes.FitType;

import java.util.ArrayList;
import java.util.List;

public class Template9 {
    public static void init(List<TemplateRes> resList, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo;
        List<LibCollagePoint> lstCollagePoints;
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_1", FitType.TITLE, "template/g9_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(290, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(330, 358));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 390));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(290, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(620, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(660, 322));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(330, 358));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(616, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 288));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(656, 324));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 388));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(330, 356));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(370, 678));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 714));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(330, 356));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(660, 322));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(696, 646));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(370, 682));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(658, 322));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 288));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 618));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(694, 648));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 710));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(370, 676));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(412, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(370, 678));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(696, 646));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(742, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(412, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(696, 646));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(1027, 616));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(1027, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(742, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_n_1", FitType.TITLE, "template/g9_n_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(408, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(372, 320));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 286));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(408, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(736, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(696, 352));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(372, 320));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(736, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 382));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(696, 352));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 286));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(372, 320));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(330, 644));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 616));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(372, 320));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(696, 352));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(656, 678));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(330, 644));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(696, 352));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 382));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 710));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(656, 678));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 616));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(330, 644));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(290, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(330, 644));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(656, 678));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(622, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(290, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(656, 678));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 710));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(622, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_n_2", FitType.TITLE, "template/g9_n_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(259, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(298, 296));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 259));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(259, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(762, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(720, 298));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(296, 298));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(758, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 259));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(722, 296));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(722, 298));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 259));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 762));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(722, 722));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(298, 298));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(722, 298));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(722, 722));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(298, 722));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 259));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(298, 298));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(298, 722));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 762));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 762));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(299, 722));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(259, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(298, 722));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(722, 722));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(762, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(259, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(722, 722));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 762));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(762, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_n_3", FitType.TITLE, "template/g9_n_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_2", FitType.TITLE, "template/g9_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1275));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1275));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1275));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1275));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1785));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1785));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1785));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1785));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_3", FitType.TITLE, "template/g9_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1730));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1730));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1730));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1730));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1430));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1430));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1430));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1430));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_4", FitType.TITLE, "template/g9_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_5", FitType.TITLE, "template/g9_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_7", FitType.TITLE, "template/g9_7.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_10", FitType.TITLE, "template/g9_10.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g9_11", FitType.TITLE, "template/g9_11.png", lstCollageInfo, radius, frameWidth, number));
    }
}
