package com.xiaopo.flying.puzzle.special.template;


import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes.FitType;

import java.util.ArrayList;
import java.util.List;

public class Template12 {
    public static void init(List<TemplateRes> resList, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo = new ArrayList<>();
        List<LibCollagePoint> lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g12_1", FitType.TITLE, "template/g12_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g12_2", FitType.TITLE, "template/g12_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g12_3", FitType.TITLE, "template/g12_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1275));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1275));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1275));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1275));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1785));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1785));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1785));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1785));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g12_4", FitType.TITLE, "template/g12_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g12_5", FitType.TITLE, "template/g12_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2550));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2550));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g12_6", FitType.TITLE, "template/g12_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g12_7", FitType.TITLE, "template/g12_7.png", lstCollageInfo, radius, frameWidth, number));
    }
}
