package com.xiaopo.flying.puzzle.special.template;


import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes.FitType;

import java.util.ArrayList;
import java.util.List;

public class Template13 {
    public static void init(List<TemplateRes> resList, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo = new ArrayList<>();
        List<LibCollagePoint> lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g13_1", FitType.TITLE, "template/g13_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1430, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1430, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1430, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1430, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g13_2", FitType.TITLE, "template/g13_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2448, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g13_3", FitType.TITLE, "template/g13_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 612));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 612));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 612));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 612));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1112));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1112));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1200));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1112));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1112));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1612));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1788));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1788));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 1612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 1612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1612));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1788));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1788));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g13_4", FitType.TITLE, "template/g13_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3065, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(510, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2550, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g13_5", FitType.TITLE, "template/g13_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(800, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(800, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(800, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1460, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1460, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(800, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1460, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1460, 510));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1460, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 510));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1460, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2260, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(612, 1900));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1760));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 1760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2410));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2410));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 1900));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1224, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 2410));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2410));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1836, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //
        resList.add(TemplateManager.initAssetItem("g13_6", FitType.TITLE, "template/g13_6.png", lstCollageInfo, radius, frameWidth, number));
    }
}
