package com.xiaopo.flying.puzzle.special.template;

import android.view.accessibility.AccessibilityNodeInfo;

import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes.FitType;

import java.util.ArrayList;
import java.util.List;

public class Template6 {
    public static void init(List<TemplateRes> resList, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo = new ArrayList<>();
        List<LibCollagePoint> lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_1", FitType.TITLE, "template/g6_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 150));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(150, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(874, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 150));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(150, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(874, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 150));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(150, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 150));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(874, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_n_1", FitType.TITLE, "template/g6_n_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 150));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(150, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(874, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 150));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(150, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 874));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(874, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 150));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(874, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(150, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(150, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(874, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 874));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_n_2", FitType.TITLE, "template/g6_n_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_2", FitType.TITLE, "template/g6_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_6", FitType.TITLE, "template/g6_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_3", FitType.TITLE, "template/g6_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_4", FitType.TITLE, "template/g6_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_5", FitType.TITLE, "template/g6_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_7", FitType.TITLE, "template/g6_7.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_8", FitType.TITLE, "template/g6_8.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_9", FitType.TITLE, "template/g6_9.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1836));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1836));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1836));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1836));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 1836));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1836));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_10", FitType.TITLE, "template/g6_10.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g6_12", FitType.TITLE, "template/g6_12.png", lstCollageInfo, radius, frameWidth, number));
    }
}
