package com.xiaopo.flying.puzzle.special.template;

import android.content.Context;
import android.view.accessibility.AccessibilityNodeInfo;

import com.xiaopo.flying.puzzle.special.model.ImageRes;
import com.xiaopo.flying.puzzle.special.model.LibCollageInfo;
import com.xiaopo.flying.puzzle.special.model.LibCollagePoint;
import com.xiaopo.flying.puzzle.special.model.TemplateRes;
import com.xiaopo.flying.puzzle.special.model.ImageRes.FitType;

import java.util.ArrayList;
import java.util.List;

public class Template2 {
    public static void init(List<TemplateRes> resList, Context context, int innerFrameWidth, int outTerFrameWidth, int radius, int frameWidth, int number) {
        List<LibCollageInfo> lstCollageInfo = new ArrayList<>();
        List<LibCollagePoint> lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_2", FitType.TITLE, "template/g2_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_1", FitType.TITLE, "template/g2_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(170, 880));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1420, 880));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1420, 2860));
        lstCollagePoints.add(TemplateManager.initCollagePoint(170, 2860));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1610, 210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2860, 210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2860, 2190));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1610, 2190));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_x_3", FitType.TITLE, "template/Artboard2_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(240, 200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2210, 200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2210, 1430));
        lstCollagePoints.add(TemplateManager.initCollagePoint(240, 1430));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(830, 1630));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2800, 1630));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2800, 2860));
        lstCollagePoints.add(TemplateManager.initCollagePoint(830, 2860));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_n_x", FitType.TITLE, "template/Artboard2_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(108, 208));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2316, 208));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2316, 2127));
        lstCollagePoints.add(TemplateManager.initCollagePoint(108, 2127));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/mask_heart1.png", context));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1682, 1723));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2950, 1723));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2950, 2869));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1682, 2869));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/mask_heart1.png", context));
        resList.add(TemplateManager.initAssetItem("g2_n_7", FitType.TITLE, "template/g2_n_7.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1744, 1744));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2591, 1744));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2591, 2591));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1744, 2591));
        LibCollageInfo libCollageInfo = new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth);
        libCollageInfo.setIsCanCorner(false);
        lstCollageInfo.add(libCollageInfo);
        //resList.add(TemplateManager.initAssetItem("g2_n_8", FitType.TITLE, "template/g2_n_8.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 340));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2720, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2720));
        lstCollagePoints.add(TemplateManager.initCollagePoint(340, 1530));
        libCollageInfo = new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth);
        libCollageInfo.setIsCanCorner(false);
        lstCollageInfo.add(libCollageInfo);
        resList.add(TemplateManager.initAssetItem("g2_n_9", FitType.TITLE, "template/g2_n_9.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(398, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2662, 760));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2720));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g2_n_10", ImageRes.FitType.TITLE, "template/g2_n_10.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(450, 906));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 284));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2610, 906));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2610, 2154));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2777));
        lstCollagePoints.add(TemplateManager.initCollagePoint(450, 2154));
        libCollageInfo = new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth);
        libCollageInfo.setIsCanCorner(false);
        lstCollageInfo.add(libCollageInfo);
        resList.add(TemplateManager.initAssetItem("g2_n_11", ImageRes.FitType.TITLE, "template/g2_n_11.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(386, 932));
        lstCollagePoints.add(TemplateManager.initCollagePoint(926, 475));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 776));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2133, 475));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2674, 932));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2674, 1740));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2756));
        lstCollagePoints.add(TemplateManager.initCollagePoint(386, 1740));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g2_n_12", ImageRes.FitType.TITLE, "template/g2_n_12.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 682));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2478));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 682));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2478));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g2_n_6", ImageRes.FitType.TITLE, "template/g2_n_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1872));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1872));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/2/g2_n_4/img1.png", context));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1188));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1188));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/2/g2_n_4/img2.png", context));
        resList.add(TemplateManager.initAssetItem("g2_n_4", ImageRes.FitType.TITLE, "template/g2_n_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1872, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1872, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/2/g2_n_5/1.png", context));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1188, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1188, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/2/g2_n_5/2.png", context));
        resList.add(TemplateManager.initAssetItem("g2_n_5", ImageRes.FitType.TITLE, "template/g2_n_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(830, 200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2800, 200));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2800, 1430));
        lstCollagePoints.add(TemplateManager.initCollagePoint(830, 1430));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(240, 1630));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2210, 1630));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2210, 2860));
        lstCollagePoints.add(TemplateManager.initCollagePoint(240, 2860));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_x_2", ImageRes.FitType.TITLE, "template/Artboard2_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(180, 210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1430, 210));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1430, 2190));
        lstCollagePoints.add(TemplateManager.initCollagePoint(180, 2190));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1640, 940));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2890, 940));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2890, 2920));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1640, 2920));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_x_4", ImageRes.FitType.TITLE, "template/Artboard2_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(220, 290));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 290));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1440, 2810));
        lstCollagePoints.add(TemplateManager.initCollagePoint(220, 2810));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1640, 290));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2840, 290));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2840, 2810));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1640, 2810));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_x_6", ImageRes.FitType.TITLE, "template/Artboard2_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(260, 180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2800, 180));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2800, 1430));
        lstCollagePoints.add(TemplateManager.initCollagePoint(260, 1430));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(260, 1620));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2800, 1620));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2800, 2870));
        lstCollagePoints.add(TemplateManager.initCollagePoint(260, 2870));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, radius, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_x_10", ImageRes.FitType.TITLE, "template/Artboard2_10.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1310));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1747, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1310, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1310, 1747));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1747, 1310));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2184, 1747));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2620, 1310, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1747, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1310, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(437, 1747, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(874, 1310));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1310, 1747));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1747, 1310));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2184, 1747, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2620, 1310, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1747));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g2_n_1", ImageRes.FitType.TITLE, "template/g2_n_1.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(765, 2295, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 2295, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1530, 1530));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 1530, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2295, 765, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 765));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g2_n_2", ImageRes.FitType.TITLE, "template/g2_n_2.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(768, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(768, 768, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 768));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_NEXT_AT_MOVEMENT_GRANULARITY, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_NEXT_AT_MOVEMENT_GRANULARITY, true));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_NEXT_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_NEXT_AT_MOVEMENT_GRANULARITY, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_NEXT_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(AccessibilityNodeInfo.ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, 768, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(768, 768, true));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(768, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollagePoints.add(TemplateManager.initCollagePoint1024(0, AccessibilityNodeInfo.ACTION_NEXT_HTML_ELEMENT));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        resList.add(TemplateManager.initAssetItem("g2_n_3", ImageRes.FitType.TITLE, "template/g2_n_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1020, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_5", ImageRes.FitType.TITLE, "template/g2_5.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(2040, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_6", ImageRes.FitType.TITLE, "template/g2_6.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1020));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_3", ImageRes.FitType.TITLE, "template/g2_3.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2040));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_4", ImageRes.FitType.TITLE, "template/g2_4.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 2295));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 10, outTerFrameWidth, innerFrameWidth));
        //resList.add(TemplateManager.initAssetItem("g2_7", ImageRes.FitType.TITLE, "template/g2_7.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1872));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1872));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/img2_9_1.png", context));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 1188));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 1188));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/img2_9_2.png", context));
        resList.add(TemplateManager.initAssetItem("g2_n_13", ImageRes.FitType.TITLE, "template/g2_n_13.png", lstCollageInfo, radius, frameWidth, number));
        lstCollageInfo = new ArrayList<>();
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(0, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1872, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1872, 0));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/img2_10_1.png", context));
        lstCollagePoints = new ArrayList<>();
        lstCollagePoints.add(TemplateManager.initCollagePoint(1188, 0));
        lstCollagePoints.add(TemplateManager.initCollagePoint(1188, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 3060));
        lstCollagePoints.add(TemplateManager.initCollagePoint(3060, 0));
        lstCollageInfo.add(new LibCollageInfo(lstCollagePoints, 0, outTerFrameWidth, outTerFrameWidth, "template/mask/img2_10_2.png", context));
        resList.add(TemplateManager.initAssetItem("g2_n_14", ImageRes.FitType.TITLE, "template/g2_n_14.png", lstCollageInfo, radius, frameWidth, number));
    }
}
